apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mydeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
   metadata:
    labels:
      app: web
   spec:
     containers:
     - name: site
       image: brunodalcas/conversao-temperatura:v1
       ports: 
       - containerPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30000
  type: NodePort
